---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: poetry-install
  namespace: tekton-resources
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    Task to install poetry wihin a workspace to later use installed dependencies
  workspaces:
    - name: source
      description: >-
        The workspace containing python source code which we want to format.
  params:
  - name: default_image
    default: image-registry.openshift-image-registry.svc:5000/tekton-resources/python-poetry:3.11
  - name: repository_url
  steps:
  - name: transform
    image: $(params.default_image)
    workingDir: $(workspaces.source.path)
    env:
      - name: POETRY_VIRTUALENVS_PATH
        value: $(workspaces.source.path)/venv
      - name: REPOSITORY_URL
        value: $(params.repository_url)
    script: |
      poetry install