---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: poetry-test
  namespace: tekton-resources
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    Task to run poetry commands in a workspace
  workspaces:
    - name: source
      description: >-
        The workspace containing python source code which we want to format.
  params:
  - name: default_image
    default: image-registry.openshift-image-registry.svc:5000/tekton-resources/python-poetry:3.11-docker
  - name: command
    description: >-
      The command to run with poetry
  steps:
  - name: poetry-run
    image: $(params.default_image)
    workingDir: $(workspaces.source.path)
    env:
      - name: POETRY_VIRTUALENVS_PATH
        value: $(workspaces.source.path)/venv
      - name: COMMAND
        value: $(params.command)
      - name: DOCKER_TLS_CERTDIR
        value: /certs
    script: |
      # Currently sleep to wait until docker has created the TLS certs
      sleep 5
      docker version
      poetry run $COMMAND
    volumeMounts:
      - mountPath: /var/run/
        name: dind-socket
      - mountPath: /certs
        name: dind-certs
  sidecars:
  - image: docker:24.0.5-dind
    name: docker
    env:
      - name: DOCKER_TLS_CERTDIR
        value: /certs
    securityContext:
      privileged: true
      runAsNonRoot: false
    volumeMounts:
      - mountPath: /var/lib/docker
        name: dind-storage
      - mountPath: /var/run/
        name: dind-socket
      - mountPath: /certs
        name: dind-certs
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}
    - name: dind-certs
      emptyDir: {}