---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: poetry-run
  namespace: tekton-resources
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    Task to run poetry commands in a workspace
  workspaces:
    - name: source
      description: >-
        The workspace containing python source code which we want to format.
  params:
  - name: default_image
    default: python:3.11
  - name: command
    description: >-
      The command to run with poetry
  steps:
  - name: poetry-run
    image: $(params.default_image)
    workingDir: $(workspaces.source.path)
    env:
      - name: POETRY_VIRTUALENVS_PATH
        value: $(workspaces.source.path)
      - name: COMMAND
        value: $(params.command)
    script: |
      pip install poetry==1.3.2
      ls -la
      env
      poetry run $COMMAND