---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-sidecar-test
  namespace: tekton-resources
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    Task to run poetry commands in a workspace
  steps:
    - image: docker.io/docker
      name: client
      script: |
        docker run hello-world
        docker images
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
  sidecars:
    - image: docker:24.0.5-dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}