apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName:  docker-sidecar-
  namespace: tekton-resources
spec:
  taskRef:
    resolver: cluster
    params:
    - name: kind
      value: task
    - name: name
      value: poetry-test
    - name: namespace
      value: tekton-resources
  params:
  - name: command
    value: pytest
  workspaces:
  - name: source
    emptyDir: {}