apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun 
spec:
  pipelineRef:
    name: git-clone
  params:
    - name: image-tag
      value: 1f3acb53eb4a4bce563c65dd0df9531518d2371-040620231523
  workspaces:
  - name: ssh-creds
    secret:
      secretName: ssh-creds
  - name: app-pvc
    persistentVolumeClaim:
      claimName: app-pvc
  - name: argo-pvc
    persistentVolumeClaim:
      claimName: argo-pvc