apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: tekton-examples
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
  volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-pvc
  namespace: tekton-examples
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
  volumeBindingMode: Immediate