apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName:  timestamp-to-timestring-
  namespace: tekton-resources
spec:
  taskRef:
    resolver: cluster
    params:
    - name: kind
      value: task
    - name: name
      value: timestamp-to-timestring
    - name: namespace
      value: tekton-resources
  params:
  - name: timestamp
    value: 1688134191